nelmio_api_doc:
    documentation:
        servers:
            - url: 127.0.0.1:8000
        info:
            title: La guilde des Seigneurs
            description: API utilisée pour la Guilde des Seigneurs
            version: "0.10"
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api|_error).*$) # Accepts routes under /api except /api/doc
